version: '3'

services:
  shop_mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: example!@3
    # {외부 노출 포트}:{도커 컨테이너 내부 포트}
    ports:
      - "13306:3306"
    volumes:
      - /var/lib/mysql

  shop_spring:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - shop_mysql
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://shop_mysql:3306/shop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example!@3
