version: '3'

services:
  database:
    container_name: practice_mysql
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: example!@3
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - bank_network

  application:
    container_name: practice_spring
    restart: on-failure
    build:
      context: ../../..
      dockerfile: ./submodule-config/Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bank_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example!@3
    depends_on:
      - database
    networks:
      - shop

networks:
  shop:
    driver: bridge
