spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: example!@3
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      #      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #        show_sql: true  # sout으로 로그 출력
        format_sql: true
        # 일대다 관계에서 컬렉션 페치 조인의 크기를 결정 (실무에서는 global 세팅을 주로 함)
        default_batch_fetch_size: 100
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  # redis 설정
  data:
    redis:
      port: 6379
      host: redis
  # 에러 메세지 양식 경로
  messages:
    basename: errors

server:
  port: 9000

logging:
  level:
    org.springframework.boot.autoconfigure.thymeleaf: DEBUG
    org.hibernate.SQL: debug  # logger를 통해 로그 출력
    org.hibernate.orm.jdbc.bind: trace  # 스프링 3.0 + hibernate 6 기준

#==========커스텀 변수============#
jwt:
  secret: SUPERSECRET
  access-token-subject: access-token
  refresh-token-subject: refresh-token
  admin-subject: admin
  access-token-expiration-in-seconds: 1800  # 30분
  refresh-token-expiration-in-seconds: 1209600  # 14일

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shop_mysql:3306/shop
    username: root
    password: example!@3
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  # redis 설정
  data:
    redis:
      port: 6379
      host: redis
  # 에러 메세지 양식 경로
  messages:
    basename: errors

server:
  port: 9001

logging:
  level:
    org.springframework.boot.autoconfigure.thymeleaf: DEBUG
    org.hibernate.SQL: debug  # logger를 통해 로그 출력
    org.hibernate.orm.jdbc.bind: trace  # 스프링 3.0 + hibernate 6 기준

#==========커스텀 변수============#
jwt:
  secret: SECRET
  access-token-expiration-in-seconds: 1800  # 30분
  refresh-token-expiration-in-seconds: 1209600  # 14일
